In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence) - 1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [3]:
model = keras.models.Sequential()
model.add(keras.layers.LSTM(50,activation='relu', input_shape=(3,1)))
model.add(keras.layers.Dense(1))
model.compile(optimizer='adam',loss='mse')

In [4]:
X = X.reshape(-1,3,1)

In [5]:
model.fit(X,y,epochs=200)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 4724.5874
Epoch 2/200
1/1 [==============================] - 0s 13ms/step - loss: 4664.6958
Epoch 3/200
1/1 [==============================] - 0s 11ms/step - loss: 4606.5820
Epoch 4/200
1/1 [==============================] - 0s 10ms/step - loss: 4550.1450
Epoch 5/200
1/1 [==============================] - 0s 12ms/step - loss: 4495.3481
Epoch 6/200
1/1 [==============================] - 0s 16ms/step - loss: 4442.2949
Epoch 7/200
1/1 [==============================] - 0s 11ms/step - loss: 4390.9185
Epoch 8/200
1/1 [==============================] - 0s 12ms/step - loss: 4341.1060
Epoch 9/200
1/1 [==============================] - 0s 11ms/step - loss: 4293.1069
Epoch 10/200
1/1 [==============================] - 0s 11ms/step - loss: 4246.6348
Epoch 11/200
1/1 [==============================] - 0s 13ms/step - loss: 4201.5044
Epoch 12/200
1/1 [==============================] - 0s 11ms/step - loss: 4157.5991
Epoch 13/200
1/

In [6]:
x_input = np.array([70,80,90])
x_input = x_input.reshape(-1,3,1)
y_hat = model.predict(x_input)

In [7]:
y_hat

array([[101.98096]], dtype=float32)

In [8]:
model2 = keras.models.Sequential()
model2.add(keras.layers.LSTM(50, activation='relu', return_sequences=True, input_shape=(3,1)))
model2.add(keras.layers.LSTM(50, activation='relu'))
model2.add(keras.layers.Dense(1))
model2.compile(optimizer='adam', loss='mse')

model2.fit(X,y, epochs=200)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 4463.9702
Epoch 2/200
1/1 [==============================] - 0s 18ms/step - loss: 4432.7974
Epoch 3/200
1/1 [==============================] - 0s 18ms/step - loss: 4400.7798
Epoch 4/200
1/1 [==============================] - 0s 15ms/step - loss: 4367.3257
Epoch 5/200
1/1 [==============================] - 0s 16ms/step - loss: 4331.6074
Epoch 6/200
1/1 [==============================] - 0s 16ms/step - loss: 4292.8438
Epoch 7/200
1/1 [==============================] - 0s 20ms/step - loss: 4250.4932
Epoch 8/200
1/1 [==============================] - 0s 21ms/step - loss: 4204.0376
Epoch 9/200
1/1 [==============================] - 0s 19ms/step - loss: 4152.8853
Epoch 10/200
1/1 [==============================] - 0s 20ms/step - loss: 4096.4312
Epoch 11/200
1/1 [==============================] - 0s 13ms/step - loss: 4034.0784
Epoch 12/200
1/1 [==============================] - 0s 20ms/step - loss: 3965.3203
Epoch 13/200
1/

In [15]:
y_hat = model2.predict(x_input)
print(y_hat)

[[100.62638]]


In [9]:
model3 = keras.models.Sequential()
model3.add(keras.layers.Bidirectional(keras.layers.LSTM(50, activation='relu'), input_shape=(3,1)))
model3.add(keras.layers.Dense(1))
model3.compile(optimizer='adam', loss='mse')
model3.fit(X, y, epochs=200)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 4009.0408
Epoch 2/200
1/1 [==============================] - 0s 20ms/step - loss: 3922.1506
Epoch 3/200
1/1 [==============================] - 0s 19ms/step - loss: 3834.9812
Epoch 4/200
1/1 [==============================] - 0s 14ms/step - loss: 3747.1543
Epoch 5/200
1/1 [==============================] - 0s 16ms/step - loss: 3658.4011
Epoch 6/200
1/1 [==============================] - 0s 15ms/step - loss: 3568.4551
Epoch 7/200
1/1 [==============================] - 0s 17ms/step - loss: 3477.0254
Epoch 8/200
1/1 [==============================] - 0s 12ms/step - loss: 3383.8269
Epoch 9/200
1/1 [==============================] - 0s 16ms/step - loss: 3288.5422
Epoch 10/200
1/1 [==============================] - 0s 16ms/step - loss: 3190.9216
Epoch 11/200
1/1 [==============================] - 0s 18ms/step - loss: 3090.7908
Epoch 12/200
1/1 [==============================] - 0s 18ms/step - loss: 2988.0586
Epoch 13/200
1/

In [10]:
y_hat = model3.predict(x_input)
print(y_hat)

[[101.638824]]


In [11]:
n_steps = 4
X, y = split_sequence(raw_seq, n_steps)
n_features = 1
n_seq = 2
n_steps = 2
X = X.reshape((X.shape[0], n_seq, n_steps, n_features))

In [13]:
model4 = keras.models.Sequential()
model4.add(keras.layers.TimeDistributed(
                keras.layers.Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, 2, 1)))
model4.add(keras.layers.TimeDistributed(
                keras.layers.MaxPooling1D(pool_size=2)))
model4.add(keras.layers.TimeDistributed(
                keras.layers.Flatten()))
model4.add(keras.layers.LSTM(50, activation='relu'))
model4.add(keras.layers.Dense(1))
model4.compile(optimizer='adam', loss='mse')

model4.fit(X, y, epochs=500)

Epoch 1/500


NotFoundError:  No algorithm worked!
	 [[node sequential_4/time_distributed_3/conv1d_1/conv1d (defined at <ipython-input-13-858da4c9766f>:12) ]] [Op:__inference_train_function_15088]

Function call stack:
train_function


In [23]:
x_input = np.array([60, 70, 80, 90])
x_input = x_input.reshape(1,2,2,1)
y_hat = model4.predict(x_input)
print(y_hat)

[[102.7476]]


In [30]:
X,y = split_sequence(raw_seq, 4)
X = X.reshape(-1, 2, 1, 2, 1)
model5 = keras.models.Sequential()
model5.add(keras.layers.ConvLSTM2D(filters=64, kernel_size=(1,2), activation='relu', input_shape=(2,1,2,1)))
model5.add(keras.layers.Flatten())
model5.add(keras.layers.Dense(1))
model5.compile(optimizer='adam', loss='mse')
model5.fit(X, y, epochs=500)

Epoch 1/500
5/5 [==============================] - 0s - loss: 5150.5869
Epoch 2/500
5/5 [==============================] - 0s - loss: 5107.5293
Epoch 3/500
5/5 [==============================] - 0s - loss: 5059.0713
Epoch 4/500
5/5 [==============================] - 0s - loss: 5012.1187
Epoch 5/500
5/5 [==============================] - 0s - loss: 4966.7373
Epoch 6/500
5/5 [==============================] - 0s - loss: 4923.4727
Epoch 7/500
5/5 [==============================] - 0s - loss: 4882.7822
Epoch 8/500
5/5 [==============================] - 0s - loss: 4845.2959
Epoch 9/500
5/5 [==============================] - 0s - loss: 4811.9678
Epoch 10/500
5/5 [==============================] - 0s - loss: 4781.4834
Epoch 11/500
5/5 [==============================] - 0s - loss: 4750.8696
Epoch 12/500
5/5 [==============================] - 0s - loss: 4722.2397
Epoch 13/500
5/5 [==============================] - 0s - loss: 4694.0059
Epoch 14/500
5/5 [==============================] - 0s - los

In [32]:
x_input = np.array([60, 70, 80, 90])
x_input = x_input.reshape(-1,2,1,2,1)
y_hat = model5.predict(x_input)
print(y_hat)

[[103.63388]]


In [33]:
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([ in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
in_seq1 = in_seq1.reshape((len(in_seq1),1))
in_seq2 = in_seq2.reshape((len(in_seq2),1))
out_seq = out_seq.reshape((len(out_seq),1))
dataset = np.hstack((in_seq1, in_seq2, out_seq))
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [34]:
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps
        if end_ix > len(sequences):
            break
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1,-1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
X, y = split_sequences(dataset, 3)
print(X.shape, y.shape)
for i in range(len(X)):
    print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [42]:
model6 = keras.models.Sequential()
model6.add(keras.layers.LSTM(50, activation='relu', input_shape=(3,2)))
model6.add(keras.layers.Dense(1))
model6.compile(optimizer='adam', loss='mse')

model6.fit(X,y,epochs=200)

Epoch 1/200
7/7 [==============================] - 1s - loss: 17088.9062
Epoch 2/200
7/7 [==============================] - 0s - loss: 16939.6309
Epoch 3/200
7/7 [==============================] - 0s - loss: 16772.1133
Epoch 4/200
7/7 [==============================] - 0s - loss: 16598.5645
Epoch 5/200
7/7 [==============================] - 0s - loss: 16422.2402
Epoch 6/200
7/7 [==============================] - 0s - loss: 16242.3066
Epoch 7/200
7/7 [==============================] - 0s - loss: 16059.6143
Epoch 8/200
7/7 [==============================] - 0s - loss: 15878.6797
Epoch 9/200
7/7 [==============================] - 0s - loss: 15697.7051
Epoch 10/200
7/7 [==============================] - 0s - loss: 15510.3799
Epoch 11/200
7/7 [==============================] - 0s - loss: 15315.6162
Epoch 12/200
7/7 [==============================] - 0s - loss: 15117.9111
Epoch 13/200
7/7 [==============================] - 0s - loss: 14912.9912
Epoch 14/200
7/7 [=============================

In [43]:
x_input = np.array([[80,85],[90,95],[100,105]])
x_input = x_input.reshape(1,3,2)
yhat = model6.predict(x_input)
print(yhat)

[[209.9487]]


In [44]:
def split_sequences(sequences, n_steps):
    X, y= list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps
        if end_ix > len(sequences)-1:
            break
        seq_x , seq_y = sequences[i:end_ix,:], sequences[end_ix,:]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [45]:
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
in_seq1 = in_seq1.reshape(len(in_seq1),1)
in_seq2 = in_seq2.reshape(len(in_seq2),1)
out_seq = out_seq.reshape(len(out_seq),1)

dataset = np.hstack((in_seq1,in_seq2, out_seq))
X,y = split_sequences(dataset, 3)
print(X.shape, y.shape)
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [49]:
model7 = keras.models.Sequential()
model7.add(keras.layers.LSTM(100, activation='relu', return_sequences=True, input_shape=(3,3)))
model7.add(keras.layers.LSTM(100, activation='relu'))
model7.add(keras.layers.Dense(3))
model7.compile(optimizer='adam', loss='mse')

model7.fit(X, y, epochs=400)

Epoch 1/400
6/6 [==============================] - 1s - loss: 9646.3457
Epoch 2/400
6/6 [==============================] - 0s - loss: 9554.9346
Epoch 3/400
6/6 [==============================] - 0s - loss: 9461.6465
Epoch 4/400
6/6 [==============================] - 0s - loss: 9359.6201
Epoch 5/400
6/6 [==============================] - 0s - loss: 9240.8359
Epoch 6/400
6/6 [==============================] - 0s - loss: 9103.7578
Epoch 7/400
6/6 [==============================] - 0s - loss: 8950.4775
Epoch 8/400
6/6 [==============================] - 0s - loss: 8770.8701
Epoch 9/400
6/6 [==============================] - 0s - loss: 8552.6963
Epoch 10/400
6/6 [==============================] - 0s - loss: 8275.4336
Epoch 11/400
6/6 [==============================] - 0s - loss: 7944.5781
Epoch 12/400
6/6 [==============================] - 0s - loss: 7532.9805
Epoch 13/400
6/6 [==============================] - 0s - loss: 7005.3809
Epoch 14/400
6/6 [==============================] - 0s - los

In [50]:
x_input = np.array([[70, 75, 145], [80, 85, 165], [90, 95, 185]])
x_input = x_input.reshape(-1, 3, 3)
yhat = model7.predict(x_input)
print(yhat)

[[103.52934 108.85267 213.30876]]


In [56]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y= list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        if out_end_ix > len(sequence):
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
X, y = split_sequence(raw_seq, 3, 2)
for i in range(len(X)):
    print(X[i], y[i])
X = X.reshape(*X.shape,1)

[10 20 30] [40 50]
[20 30 40] [50 60]
[30 40 50] [60 70]
[40 50 60] [70 80]
[50 60 70] [80 90]


In [68]:
model8 = keras.models.Sequential()
model8.add(keras.layers.LSTM(100,
                            activation='relu',
                            return_sequences=True,
                            input_shape=(3,1)))
model8.add(keras.layers.LSTM(100,
                            activation='relu',
                            ))
model8.add(keras.layers.Dense(2))
model8.compile(optimizer='adam',loss='mse')
model8.fit(X,y,epochs=500)

Epoch 1/500
5/5 [==============================] - 2s - loss: 4399.0483
Epoch 2/500
5/5 [==============================] - 0s - loss: 4344.2446
Epoch 3/500
5/5 [==============================] - 0s - loss: 4266.5044
Epoch 4/500
5/5 [==============================] - 0s - loss: 4189.0396
Epoch 5/500
5/5 [==============================] - 0s - loss: 4103.7861
Epoch 6/500
5/5 [==============================] - 0s - loss: 4005.2527
Epoch 7/500
5/5 [==============================] - 0s - loss: 3897.6099
Epoch 8/500
5/5 [==============================] - 0s - loss: 3769.8413
Epoch 9/500
5/5 [==============================] - 0s - loss: 3619.4446
Epoch 10/500
5/5 [==============================] - 0s - loss: 3444.5488
Epoch 11/500
5/5 [==============================] - 0s - loss: 3240.0698
Epoch 12/500
5/5 [==============================] - 0s - loss: 3009.1094
Epoch 13/500
5/5 [==============================] - 0s - loss: 2752.1506
Epoch 14/500
5/5 [==============================] - 0s - los

In [69]:
x_input = np.array([70, 80, 90])
x_input = x_input.reshape(-1, 3, 1)
yhat = model8.predict(x_input)
print(yhat)

[[105.60182  117.266716]]


In [72]:
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        if out_end_ix > len(sequence):
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

X, y = split_sequence(raw_seq, 3, 2)
X = X.reshape(*X.shape ,1)
y = y.reshape(*y.shape ,1)
model10 = keras.models.Sequential()
model10.add(keras.layers.LSTM(100, activation='relu', input_shape=(3, 1)))
model10.add(keras.layers.RepeatVector(2))
model10.add(keras.layers.LSTM(100, activation='relu', return_sequences=True))
model10.add(keras.layers.TimeDistributed(
                keras.layers.Dense(1)))
model10.compile(optimizer='adam', loss='mse')
model10.fit(X, y, epochs=100)

Epoch 1/100
5/5 [==============================] - 2s - loss: 4236.8354
Epoch 2/100
5/5 [==============================] - 0s - loss: 4166.1968
Epoch 3/100
5/5 [==============================] - 0s - loss: 4078.3015
Epoch 4/100
5/5 [==============================] - 0s - loss: 3975.3645
Epoch 5/100
5/5 [==============================] - 0s - loss: 3854.4402
Epoch 6/100
5/5 [==============================] - 0s - loss: 3716.7837
Epoch 7/100
5/5 [==============================] - 0s - loss: 3554.0481
Epoch 8/100
5/5 [==============================] - 0s - loss: 3365.2656
Epoch 9/100
5/5 [==============================] - 0s - loss: 3156.6802
Epoch 10/100
5/5 [==============================] - 0s - loss: 2930.7996
Epoch 11/100
5/5 [==============================] - 0s - loss: 2679.7285
Epoch 12/100
5/5 [==============================] - 0s - loss: 2397.3940
Epoch 13/100
5/5 [==============================] - 0s - loss: 2087.2832
Epoch 14/100
5/5 [==============================] - 0s - los

In [73]:
x_input = np.array([70, 80, 90])
x_input = x_input.reshape(1, 3, 1)
yhat = model10.predict(x_input)
print(yhat)

[[[104.85403]
  [118.9263 ]]]


In [76]:
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out-1
        if out_end_ix > len(sequences):
            break
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix:, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
in_seq1 = in_seq1.reshape(-1,1)
in_seq2 = in_seq2.reshape(-1,1)
out_seq = out_seq.reshape(-1,1)
dataset = np.hstack((in_seq1, in_seq2, out_seq))

X,y = split_sequences(dataset, 3, 2)
print(X.shape, y.shape)
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 2) (6, 2)
[[10 15]
 [20 25]
 [30 35]] [65 85]
[[20 25]
 [30 35]
 [40 45]] [ 85 105]
[[30 35]
 [40 45]
 [50 55]] [105 125]
[[40 45]
 [50 55]
 [60 65]] [125 145]
[[50 55]
 [60 65]
 [70 75]] [145 165]
[[60 65]
 [70 75]
 [80 85]] [165 185]


In [77]:
model11 = keras.models.Sequential()
model11.add(keras.layers.LSTM(100, activation='relu',return_sequences=True, input_shape=(3,2)))
model11.add(keras.layers.LSTM(100, activation='relu'))
model11.add(keras.layers.Dense(2))
model11.compile(optimizer='adam', loss='mse')
model11.fit(X, y, epochs=200)

Epoch 1/200
6/6 [==============================] - 2s - loss: 17195.8848
Epoch 2/200
6/6 [==============================] - 0s - loss: 17009.8105
Epoch 3/200
6/6 [==============================] - 0s - loss: 16797.4551
Epoch 4/200
6/6 [==============================] - 0s - loss: 16542.0352
Epoch 5/200
6/6 [==============================] - 0s - loss: 16294.8389
Epoch 6/200
6/6 [==============================] - 0s - loss: 16027.0596
Epoch 7/200
6/6 [==============================] - 0s - loss: 15745.6914
Epoch 8/200
6/6 [==============================] - 0s - loss: 15448.3711
Epoch 9/200
6/6 [==============================] - 0s - loss: 15121.4326
Epoch 10/200
6/6 [==============================] - 0s - loss: 14746.1396
Epoch 11/200
6/6 [==============================] - 0s - loss: 14331.6982
Epoch 12/200
6/6 [==============================] - 0s - loss: 13847.9814
Epoch 13/200
6/6 [==============================] - 0s - loss: 13277.7217
Epoch 14/200
6/6 [=============================

In [79]:
x_input = np.array([[70,75], [80,85], [90,95]])
x_input = x_input.reshape(1,3,2)
yhat = model11.predict(x_input)
print(yhat)

[[186.07428 207.40161]]


In [80]:
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        if out_end_ix > len(sequences):
            break
        seq_x, seq_y = sequences[i:end_ix,:], sequences[end_ix:out_end_ix,:]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
in_seq1 = in_seq1.reshape(-1,1)
in_seq2 = in_seq2.reshape(-1,1)
out_seq = out_seq.reshape(-1,1)

dataset = np.hstack((in_seq1, in_seq2, out_seq))
X,y = split_sequences(dataset, 3, 2)
print(X.shape, y.shape)
for i in range(len(X)):
    print(X[i], y[i])

(5, 3, 3) (5, 2, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [[ 40  45  85]
 [ 50  55 105]]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [[ 50  55 105]
 [ 60  65 125]]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [[ 60  65 125]
 [ 70  75 145]]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [[ 70  75 145]
 [ 80  85 165]]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [[ 80  85 165]
 [ 90  95 185]]


In [83]:
model12 = keras.models.Sequential()
model12.add(keras.layers.LSTM(200, activation='relu', input_shape=(3,3)))
model12.add(keras.layers.RepeatVector(2))
model12.add(keras.layers.LSTM(200, activation='relu', return_sequences=True))
model12.add(keras.layers.TimeDistributed(
                keras.layers.Dense(3)))
model12.compile(optimizer='adam', loss='mse')

model12.fit(X, y, epochs=300)


Epoch 1/300
5/5 [==============================] - 3s - loss: 9716.7646
Epoch 2/300
5/5 [==============================] - 0s - loss: 9565.4404
Epoch 3/300
5/5 [==============================] - 0s - loss: 9418.4043
Epoch 4/300
5/5 [==============================] - 0s - loss: 9260.3750
Epoch 5/300
5/5 [==============================] - 0s - loss: 9056.1016
Epoch 6/300
5/5 [==============================] - 0s - loss: 8779.2305
Epoch 7/300
5/5 [==============================] - 0s - loss: 8398.4570
Epoch 8/300
5/5 [==============================] - 0s - loss: 7904.0532
Epoch 9/300
5/5 [==============================] - 0s - loss: 7275.2954
Epoch 10/300
5/5 [==============================] - 0s - loss: 6532.9097
Epoch 11/300
5/5 [==============================] - 0s - loss: 5662.9062
Epoch 12/300
5/5 [==============================] - 0s - loss: 4695.9824
Epoch 13/300
5/5 [==============================] - 0s - loss: 3693.9868
Epoch 14/300
5/5 [==============================] - 0s - los

In [84]:
x_input = np.array([[60, 65, 125], [70, 75, 145], [80, 85, 165]])
x_input = x_input.reshape(1, 3, 3)
yhat = model12.predict(x_input)
print(yhat)

[[[ 91.743454  96.93921  188.1097  ]
  [101.65989  106.712135 209.42671 ]]]
